package com.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-04-19T16:02:05.164-05:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "http://webservice.com/", name = "IOperaciones")
@XmlSeeAlso({ObjectFactory.class})
public interface IOperaciones {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "suma", targetNamespace = "http://webservice.com/", className = "com.webservice.client.Suma")
    @WebMethod(action = "urn:Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.client.SumaResponse")
    public int suma(
        @WebParam(name = "valorNumerico1", targetNamespace = "")
        int valorNumerico1,
        @WebParam(name = "valorNumerico2", targetNamespace = "")
        int valorNumerico2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "resta", targetNamespace = "http://webservice.com/", className = "com.webservice.client.Resta")
    @WebMethod(action = "urn:Resta")
    @ResponseWrapper(localName = "restaResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.client.RestaResponse")
    public int resta(
        @WebParam(name = "valorNumerico1", targetNamespace = "")
        int valorNumerico1,
        @WebParam(name = "valorNumerico2", targetNamespace = "")
        int valorNumerico2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://webservice.com/", className = "com.webservice.client.Divide")
    @WebMethod(action = "urn:Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.client.DivideResponse")
    public int divide(
        @WebParam(name = "valorNumerico1", targetNamespace = "")
        int valorNumerico1,
        @WebParam(name = "valorNumerico2", targetNamespace = "")
        int valorNumerico2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "multiplica", targetNamespace = "http://webservice.com/", className = "com.webservice.client.Multiplica")
    @WebMethod(action = "urn:Multiplica")
    @ResponseWrapper(localName = "multiplicaResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.client.MultiplicaResponse")
    public int multiplica(
        @WebParam(name = "valorNumerico1", targetNamespace = "")
        int valorNumerico1,
        @WebParam(name = "valorNumerico2", targetNamespace = "")
        int valorNumerico2
    );
}
