package com.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-04-19T16:02:05.223-05:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebServiceClient(name = "OperacionesImplService", 
                  wsdlLocation = "file:/Volumes/HD2/tools/Proyectos/Pruebas/ObtenerCoordenadas/WebServiceOperacionesClient/WebContent/WEB-INF/wsdl/OperacionesImplService.wsdl",
                  targetNamespace = "http://webservice.com/") 
public class OperacionesImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.com/", "OperacionesImplService");
    public final static QName OperacionesImplPort = new QName("http://webservice.com/", "OperacionesImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Volumes/HD2/tools/Proyectos/Pruebas/ObtenerCoordenadas/WebServiceOperacionesClient/WebContent/WEB-INF/wsdl/OperacionesImplService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperacionesImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Volumes/HD2/tools/Proyectos/Pruebas/ObtenerCoordenadas/WebServiceOperacionesClient/WebContent/WEB-INF/wsdl/OperacionesImplService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperacionesImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperacionesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionesImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperacionesImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperacionesImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperacionesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IOperaciones
     */
    @WebEndpoint(name = "OperacionesImplPort")
    public IOperaciones getOperacionesImplPort() {
        return super.getPort(OperacionesImplPort, IOperaciones.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOperaciones
     */
    @WebEndpoint(name = "OperacionesImplPort")
    public IOperaciones getOperacionesImplPort(WebServiceFeature... features) {
        return super.getPort(OperacionesImplPort, IOperaciones.class, features);
    }

}
